# Generated by Django 3.0.5 on 2020-04-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='body',
            field=models.TextField(default=None),
        ),
    ]
